export default {
  shopNow: 'Shop Now',
  welcomeMessage: 'Welcome to eKart',
  bannerMessage: 'Shop Gadgets and Accessories',
  shopNowBtn: 'SHOP NOW',
  categoriesLabel: 'Categories',
  recommendedLabel: 'Recommended for you',
  searchBarText: 'Search Here...',
  searchProducts: 'Search Products',
  HomeTabName: 'Home',
  accountsTabName: 'Accounts',
  logoutTabName: 'Logout',
  descriptionLabel: 'Description',
  addToCartBtnText: 'Add To Cart',
  subTotalLabel: 'Sub Total',
  yourCartLabel: 'Your Cart',
  emailInvalidMessage: 'enter Valid email eg: john@123.com',
  passwordInvalidMessage: ' please enter Valid Password eg: John@123',
  loginBtnText: 'LOGIN',
  saveDetailsBtn: 'Save Details',
  editUserInfo: 'Edit User Info',
  cancelBtn: 'Cancel',
  saveChanges: 'Save Changes',
  splashScreenMessage: 'Fetching User Info please wait...',
  loginToContinue: 'Login to Continue',
  productDiscountText: '10% Off',
  welcomeMessage: 'Welcome to Ebay',
  checkOutBtnText: 'Buy now',
  home: 'Home',
  logout: 'Logout',
  accounts: 'Accounts',
  all: 'All',
  searchResultsText: 'Search Results...',
  orderDetails: 'Order Details',
  searchScreenHeader: 'Search Products',
  productDetailsHeader: 'Product Details ',
  orderSuccessFull: 'Order Placed Successfully !',
  notAUser: 'Not a user? Sign up',
  signUp: 'Signup to continue',
  register: 'Register',
  alreadyUser: 'Already registered? Login',
  totalProducts: 'Total Products',
  paymentStatus: 'Payment Status',
  orderId: 'Order Id',
  orderValue: 'Order value',
  totalQuantity: 'Total Quantity',
  orderSummary: 'Order Summary',
  yourOrders: 'Your Orders!',
  ordersHistory: 'Orders History',
  shippingFee: 'Shipping fee',
  shippingFeeValue: '£ 0',
  totalWithTax: 'Total with Tax',
  addPromoText: 'Add Promo Code',
  invalidCredentials: 'Invalid credentials !',
  proceedToCheckout: 'Proceed to Checkout',
  empty: '',
  lemaans:"Lemaan",
  deliveryAddress: 'Delivery Address',
  dataSavedSuccessfully: 'Data saved sucessfully !',
  inValidPassword: 'Invalid password!',
  noUsersFound: 'No users found with this email!',

  navigationRoutes: {
    HomeStack: 'HOMESTACK',
    CartStack: 'CARTSTACK',
    HomeScreen: 'HOMESCREEN',
    CartScreen: 'CARTSCREEN',
    SearchScreen: 'SEARCHSCREEN',
    ProductDetailsScreen: 'PRODUCTDETAILSSCREEN',
    OrderDetailsScreen: 'ORDERDETAILSSCREEN',
    OrderListScreen: 'ORDERLISTSCREEN',
    LoginScreen: 'LOGINSCREEN',
    SignUpScreen: 'SIGNUPSCREEN',
    BottomTabs: 'BOTTOMTABS',
  },
  promiseResponses: {
    fulfilled: 'fulfilled',
    pending: 'pending',
    rejected: 'rejected',
  },

  inputFieldNames: {
    email: 'email',
    firstname: 'firstname',
    lastname: 'lastname',
    password: 'password',
  },

  loaderSizes: {
    small: 'small',
    large: 'large',
  },

  yupErrors: {
    emailError: 'Please enter valid email',
    passwordEmpty: 'Please enter your password',
    passwordInvalid:
      'Password must contain at least 8 characters, one uppercase, one number and one special case character',
    nameInvalid: 'Please enter valid name',
    contactInvalid: 'Contact number should be 10 digits',
  },
};
